[general]
# automatyczne przeładowanie przy zmianie pliku
live_config_reload = true

[window]
# dynamic title
dynamic_title = true

[window.padding]
x = 2
y = 2

[font]
# domyślny rozmiar
size = 13.0

[font.normal]
family = "Monospace"
style = "Regular"

[colors.primary]
background = "0x000320"
foreground = "0xffffff"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"  # neonowy różowy
green   = "#a6e3a1"  # pastelowa zieleń
yellow  = "#f9e2af"  # jasny żółty
blue    = "#89b4fa"  # jasnoniebieski
magenta = "#f5c2e7"  # pastelowy magenta
cyan    = "#94e2d5"  # jasny cyan
white   = "#a6adc8"  # delikatny biały

[colors.bright]
black   = "#4c4f69"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#cdd6f4"
